### ISSUE TITLE
Schreiben auf den Controller

### ISSUE THREAD

**Issue by interruptor02** [lauff/ioBroker.rct#9]
Hi

ist es auch möglich etwas an den Controller zu schreiben? Ich würde gerne etwas schreiben, dass wenn das Auto geladen wird, der Speicher nicht genutzt wird. Oder einfach ausgemacht wird.

**Comment by lauff** [comment]
Generell wäre es auch möglich in den Controller zu schreiben. Die Funktion habe ich allerdings nicht implementiert und werden kurzfristig auch nicht dazukommen. Wenn das irgendjemand anderes übernehmen möchte/kann, kann ich gerne die Dokumentation zur Verfügung stellen.
